// <auto-generated />
using System;
using Ashion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ashion.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AshionDbContext))]
    [Migration("20230816141508_addForeignKeysToReviews")]
    partial class addForeignKeysToReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShortContent")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jeans",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pants",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sweatshirts",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jackets",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shirts",
                            ProductType = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "BagsandBackpacks",
                            ProductType = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sunglasses",
                            ProductType = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jewelries",
                            ProductType = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antiagecosmetic",
                            ProductType = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Facecosmetic",
                            ProductType = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "SPF",
                            ProductType = 2
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cloth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ForKids")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShortContent")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryId = 1,
                            ColorId = 2,
                            Description = "Този продукт е направен от рециклирани материали, които са създадени чрез повторна употреба на материали преди или след тяхната употреба. Използването на рециклирани материали в продуктите намалява количеството на суровините и свързаните с тях отпадъци, енергия и вода при производството на първични материали.",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Tениска",
                            PackageId = "DE3F5A08-C6EA-473D-977E-975E80D2C664",
                            Price = 58.90m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nike",
                            CategoryId = 1,
                            ColorId = 11,
                            Description = "Този продукт е направен от рециклирани материали, които са създадени чрез повторна употреба на материали преди или след тяхната употреба. Използването на рециклирани материали в продуктите намалява количеството на суровините и свързаните с тях отпадъци, енергия и вода при производството на първични материали.",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Tениска",
                            PackageId = "DE3F5A08-C6EA-473D-977E-975E80D2C664",
                            Price = 58.90m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nike",
                            CategoryId = 1,
                            ColorId = 5,
                            Description = "Този продукт е направен от рециклирани материали, които са създадени чрез повторна употреба на материали преди или след тяхната употреба. Използването на рециклирани материали в продуктите намалява количеството на суровините и свързаните с тях отпадъци, енергия и вода при производството на първични материали.",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Tениска",
                            PackageId = "DE3F5A08-C6EA-473D-977E-975E80D2C664",
                            Price = 58.90m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nike",
                            CategoryId = 1,
                            ColorId = 3,
                            Description = "Този продукт е направен от рециклирани материали, които са създадени чрез повторна употреба на материали преди или след тяхната употреба. Използването на рециклирани материали в продуктите намалява количеството на суровините и свързаните с тях отпадъци, енергия и вода при производството на първични материали.",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Tениска",
                            PackageId = "DE3F5A08-C6EA-473D-977E-975E80D2C664",
                            Price = 58.90m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Polo Ralph Lauren",
                            CategoryId = 1,
                            ColorId = 11,
                            Description = "This T-Shirt is the best that Polo have ever created. Perfect for outdoor activities",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Тениска",
                            PackageId = "4C6AC916-30A6-4962-ACA9-67BFA417FF31",
                            Price = 232.90m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Polo Ralph Lauren",
                            CategoryId = 1,
                            ColorId = 5,
                            Description = "This T-Shirt is the best that Polo have ever created. Perfect for outdoor activities",
                            ForKids = false,
                            Gender = 1,
                            IsActive = true,
                            Name = "Тениска",
                            PackageId = "4C6AC916-30A6-4962-ACA9-67BFA417FF31",
                            Price = 232.90m,
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.ClothSize", b =>
                {
                    b.Property<int>("ClothId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ClothId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("ClothesSizes");

                    b.HasData(
                        new
                        {
                            ClothId = 1,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 1,
                            SizeId = 4
                        },
                        new
                        {
                            ClothId = 1,
                            SizeId = 5
                        },
                        new
                        {
                            ClothId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ClothId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ClothId = 3,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 3,
                            SizeId = 4
                        },
                        new
                        {
                            ClothId = 3,
                            SizeId = 5
                        },
                        new
                        {
                            ClothId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ClothId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ClothId = 5,
                            SizeId = 2
                        },
                        new
                        {
                            ClothId = 5,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 5,
                            SizeId = 4
                        },
                        new
                        {
                            ClothId = 5,
                            SizeId = 5
                        },
                        new
                        {
                            ClothId = 5,
                            SizeId = 6
                        },
                        new
                        {
                            ClothId = 6,
                            SizeId = 3
                        },
                        new
                        {
                            ClothId = 6,
                            SizeId = 5
                        },
                        new
                        {
                            ClothId = 6,
                            SizeId = 6
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 11,
                            Name = "White"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Yellow"
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShortContent")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cosmetics");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccessoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ClothId")
                        .HasColumnType("int");

                    b.Property<int?>("CosmeticId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("ClothId");

                    b.HasIndex("CosmeticId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClothId = 1,
                            Url = "https://cdn.aboutstatic.com/file/images/41fb7fb9af1199c00623a77930483763.png?bg=F4F4F5&quality=75&trim=1&height=800&width=600"
                        },
                        new
                        {
                            Id = 2,
                            ClothId = 1,
                            Url = "https://cdn.aboutstatic.com/file/images/079377b386685bf1b889e751cad816ee.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 3,
                            ClothId = 1,
                            Url = "https://cdn.aboutstatic.com/file/images/3f9d53b537dbd3fb3228daaf51b77bf8.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 4,
                            ClothId = 1,
                            Url = "https://cdn.aboutstatic.com/file/images/b1826275260cae21fb4f6a9090011bdb.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 5,
                            ClothId = 1,
                            Url = "https://cdn.aboutstatic.com/file/images/b30e9352ac137cb6270de8684c21a24d.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 6,
                            ClothId = 2,
                            Url = "https://cdn.aboutstatic.com/file/images/b17a10676017195d18bbcde5059355ea.png?bg=F4F4F5&quality=75&trim=1&height=800&width=600"
                        },
                        new
                        {
                            Id = 7,
                            ClothId = 2,
                            Url = "https://cdn.aboutstatic.com/file/images/37ca65e02d5645f4bc4326b3f570ad64.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 8,
                            ClothId = 2,
                            Url = "https://cdn.aboutstatic.com/file/images/cc19ba91c5fa92595df252b86b2c2758.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 9,
                            ClothId = 2,
                            Url = "https://cdn.aboutstatic.com/file/images/07ad50ea856241d21967c83e1491be93.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 10,
                            ClothId = 2,
                            Url = "https://cdn.aboutstatic.com/file/images/dc8bfc499b188b08186f598642dbd8f9.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 11,
                            ClothId = 3,
                            Url = "https://cdn.aboutstatic.com/file/images/72a5e2d58246dd4d26262e225bc4a1c4.png?bg=F4F4F5&quality=75&trim=1&height=1280&width=960"
                        },
                        new
                        {
                            Id = 12,
                            ClothId = 3,
                            Url = "https://cdn.aboutstatic.com/file/images/1c31b47d7ee4770cd07a578fa9779b3a.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 13,
                            ClothId = 3,
                            Url = "https://cdn.aboutstatic.com/file/images/1c38ffc11e729f57246d79b0cc94c53b.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 14,
                            ClothId = 3,
                            Url = "https://cdn.aboutstatic.com/file/images/6aa610ebbf8364caef76a582c18c58f4.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 15,
                            ClothId = 3,
                            Url = "https://cdn.aboutstatic.com/file/images/5505ae9c564cb0014f48f3914d243836.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 16,
                            ClothId = 4,
                            Url = "https://cdn.aboutstatic.com/file/images/b86f0e7845dd39e4b5792592370e71af.png?bg=F4F4F5&quality=75&trim=1&height=800&width=600"
                        },
                        new
                        {
                            Id = 17,
                            ClothId = 4,
                            Url = "https://cdn.aboutstatic.com/file/images/2951c11563182208d3c845c9302a81e2.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 18,
                            ClothId = 4,
                            Url = "https://cdn.aboutstatic.com/file/images/549438b849cd1df230f3c3fa8877014d.jpg?quality=75&height=800&width=600"
                        },
                        new
                        {
                            Id = 19,
                            ClothId = 4,
                            Url = "https://cdn.aboutstatic.com/file/images/90a207c2fb4f787f711b9c60a35554f3.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 20,
                            ClothId = 4,
                            Url = "https://cdn.aboutstatic.com/file/images/79a4134d533ad4cd5d20ce17fa26302f.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 21,
                            ClothId = 5,
                            Url = "https://cdn.aboutstatic.com/file/images/fc28d2511314ccc371d5bd10a4270cab.png?bg=F4F4F5&quality=75&trim=1&height=1280&width=960"
                        },
                        new
                        {
                            Id = 22,
                            ClothId = 5,
                            Url = "https://cdn.aboutstatic.com/file/images/3c7e26fd6afdf68dd464f0a18827066e.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 23,
                            ClothId = 5,
                            Url = "https://cdn.aboutstatic.com/file/images/dafb99dc5c08a4ebda9bf42670132cd8.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 24,
                            ClothId = 5,
                            Url = "https://cdn.aboutstatic.com/file/images/df5a0005dcf03e327fccb00464883441.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 25,
                            ClothId = 5,
                            Url = "https://cdn.aboutstatic.com/file/images/3c8af8455a8ade177b7b0585d40b3aec.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 26,
                            ClothId = 6,
                            Url = "https://cdn.aboutstatic.com/file/images/b10b0dcfd7fbf7cfde9b9770cd77d9f0.png?bg=F4F4F5&quality=75&trim=1&height=1280&width=960"
                        },
                        new
                        {
                            Id = 27,
                            ClothId = 6,
                            Url = "https://cdn.aboutstatic.com/file/images/35b936c2f46329051376d907d4661d75.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 28,
                            ClothId = 6,
                            Url = "https://cdn.aboutstatic.com/file/images/c4fe795025d3b6c27047562e6b07055f.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 29,
                            ClothId = 6,
                            Url = "https://cdn.aboutstatic.com/file/images/2a284b7a30e2a7d75b0bdbed888efa64.jpg?quality=75&height=1280&width=960"
                        },
                        new
                        {
                            Id = 30,
                            ClothId = 6,
                            Url = "https://cdn.aboutstatic.com/file/images/3161bda02ece8a966cdef0efdcaf9b0d.jpg?quality=75&height=1280&width=960"
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccessoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ClothId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<int?>("CosmeticId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("ClothId");

                    b.HasIndex("CosmeticId");

                    b.HasIndex("FromUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SizeNumber")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SizeNumber = "XS"
                        },
                        new
                        {
                            Id = 2,
                            SizeNumber = "S"
                        },
                        new
                        {
                            Id = 3,
                            SizeNumber = "M"
                        },
                        new
                        {
                            Id = 4,
                            SizeNumber = "L"
                        },
                        new
                        {
                            Id = 5,
                            SizeNumber = "XL"
                        },
                        new
                        {
                            Id = 6,
                            SizeNumber = "XXL"
                        });
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bcb4f072-ecca-43c9-ab26-c060c6f364e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "981383d2-737a-46b8-9f48-3dc8daeb8cdb",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Great",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@mail.com",
                            NormalizedUserName = "admin@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEP3RIZzFw6CpIqWrCIEKQIX/yn234QhZfK/eJlSPBG/37J9jHSW9/px+SEs++pVYNw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d219effd-a110-48e6-816d-ebc28561bcd3",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Accessory", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cloth", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Color", "Color")
                        .WithMany("Cloths")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.ClothSize", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Cloth", "Cloth")
                        .WithMany("Sizes")
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Size", "Size")
                        .WithMany("Cloths")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cloth");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cosmetic", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Image", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Accessory", null)
                        .WithMany("Images")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Cloth", null)
                        .WithMany("Images")
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Cosmetic", null)
                        .WithMany("Images")
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Review", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.Accessory", "Accessory")
                        .WithMany("Reviews")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Cloth", "Cloth")
                        .WithMany("Reviews")
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ashion.Infrastructure.Data.Entities.Cosmetic", "Cosmetic")
                        .WithMany("Reviews")
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ashion.Infrastructure.Data.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Cloth");

                    b.Navigation("Cosmetic");

                    b.Navigation("FromUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ashion.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ashion.Infrastructure.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Accessory", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cloth", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Color", b =>
                {
                    b.Navigation("Cloths");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Cosmetic", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Ashion.Infrastructure.Data.Entities.Size", b =>
                {
                    b.Navigation("Cloths");
                });
#pragma warning restore 612, 618
        }
    }
}
